<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UnityStubs.cs" />
    <Compile Include="UIElementsStubs.cs" />
    <Compile Include="EventBusUnityStubs.cs" />
    <Compile Include="../../Runtime/**/*.cs" />
    <Compile Include="../../Samples~/QuickStart/**/*.cs" />
    <Compile Include="../../Samples~/EventBusIntegration/Scripts/**/*.cs" />
  </ItemGroup>
</Project>
